### ISSUE TITLE
Can't get Gear model

### ISSUE THREAD

**Issue by kiokumicu** [RumataEstorish/TizenWearableWebCommon#3]
Hi!
You advice using code for get Gear model, but for me it's not working. I get undefined in model var.
`tizen.systeminfo.getPropertyValue('BUILD', function(res) { model = res.model; });`

What I doing wrong?

**Comment by RumataEstorish** [comment]
Hi! I can suggest your var model is out of scope when you try to use is;
Please, check following way:

tizen.systeminfo.getPropertyValue('BUILD', function(res) { 
alert(res.model);
model = res.model; 
});

**Comment by kiokumicu** [comment]
Thx, my mistake.
